/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'scheduled' : IDL.Null,
  'closed' : IDL.Null,
  'reviewingEvidence' : IDL.Null,
  'open' : IDL.Null,
  'awaitingCourt' : IDL.Null,
});
export const EncryptedText = IDL.Text;
export const Hearing = IDL.Record({
  'status' : Status,
  'date' : EncryptedText,
  'notes' : EncryptedText,
  'outcome' : EncryptedText,
});
export const EncryptedCase = IDL.Record({
  'status' : Status,
  'clientName' : EncryptedText,
  'caseNumber' : EncryptedText,
  'nextHearing' : EncryptedText,
  'hearings' : IDL.Vec(Hearing),
  'creationDate' : EncryptedText,
  'evidence' : IDL.Vec(EncryptedText),
  'clientContact' : EncryptedText,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'organization' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCase' : IDL.Func([EncryptedCase], [], []),
  'addEvidence' : IDL.Func([EncryptedText, EncryptedText], [], []),
  'addHearing' : IDL.Func([EncryptedText, Hearing], [], []),
  'addMultipleCases' : IDL.Func([IDL.Vec(EncryptedCase)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCase' : IDL.Func([EncryptedText], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseByNumber' : IDL.Func(
      [EncryptedText],
      [IDL.Opt(EncryptedCase)],
      ['query'],
    ),
  'getCases' : IDL.Func([], [IDL.Vec(EncryptedCase)], []),
  'getCasesByStatus' : IDL.Func([Status], [IDL.Vec(EncryptedCase)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCase' : IDL.Func([EncryptedCase], [], []),
  'updateStatus' : IDL.Func([EncryptedText, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'scheduled' : IDL.Null,
    'closed' : IDL.Null,
    'reviewingEvidence' : IDL.Null,
    'open' : IDL.Null,
    'awaitingCourt' : IDL.Null,
  });
  const EncryptedText = IDL.Text;
  const Hearing = IDL.Record({
    'status' : Status,
    'date' : EncryptedText,
    'notes' : EncryptedText,
    'outcome' : EncryptedText,
  });
  const EncryptedCase = IDL.Record({
    'status' : Status,
    'clientName' : EncryptedText,
    'caseNumber' : EncryptedText,
    'nextHearing' : EncryptedText,
    'hearings' : IDL.Vec(Hearing),
    'creationDate' : EncryptedText,
    'evidence' : IDL.Vec(EncryptedText),
    'clientContact' : EncryptedText,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'organization' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCase' : IDL.Func([EncryptedCase], [], []),
    'addEvidence' : IDL.Func([EncryptedText, EncryptedText], [], []),
    'addHearing' : IDL.Func([EncryptedText, Hearing], [], []),
    'addMultipleCases' : IDL.Func([IDL.Vec(EncryptedCase)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCase' : IDL.Func([EncryptedText], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseByNumber' : IDL.Func(
        [EncryptedText],
        [IDL.Opt(EncryptedCase)],
        ['query'],
      ),
    'getCases' : IDL.Func([], [IDL.Vec(EncryptedCase)], []),
    'getCasesByStatus' : IDL.Func(
        [Status],
        [IDL.Vec(EncryptedCase)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCase' : IDL.Func([EncryptedCase], [], []),
    'updateStatus' : IDL.Func([EncryptedText, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };