/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EncryptedCase {
  'status' : Status,
  'clientName' : EncryptedText,
  'caseNumber' : EncryptedText,
  'nextHearing' : EncryptedText,
  'hearings' : Array<Hearing>,
  'creationDate' : EncryptedText,
  'evidence' : Array<EncryptedText>,
  'clientContact' : EncryptedText,
}
export type EncryptedText = string;
export interface Hearing {
  'status' : Status,
  'date' : EncryptedText,
  'notes' : EncryptedText,
  'outcome' : EncryptedText,
}
export type Status = { 'scheduled' : null } |
  { 'closed' : null } |
  { 'reviewingEvidence' : null } |
  { 'open' : null } |
  { 'awaitingCourt' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'organization' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCase' : ActorMethod<[EncryptedCase], undefined>,
  'addEvidence' : ActorMethod<[EncryptedText, EncryptedText], undefined>,
  'addHearing' : ActorMethod<[EncryptedText, Hearing], undefined>,
  'addMultipleCases' : ActorMethod<[Array<EncryptedCase>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCase' : ActorMethod<[EncryptedText], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseByNumber' : ActorMethod<[EncryptedText], [] | [EncryptedCase]>,
  'getCases' : ActorMethod<[], Array<EncryptedCase>>,
  'getCasesByStatus' : ActorMethod<[Status], Array<EncryptedCase>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCase' : ActorMethod<[EncryptedCase], undefined>,
  'updateStatus' : ActorMethod<[EncryptedText, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];