/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Hearing {
    status: Status;
    date: EncryptedText;
    notes: EncryptedText;
    outcome: EncryptedText;
}
export interface EncryptedCase {
    status: Status;
    clientName: EncryptedText;
    caseNumber: EncryptedText;
    nextHearing: EncryptedText;
    hearings: Array<Hearing>;
    creationDate: EncryptedText;
    evidence: Array<EncryptedText>;
    clientContact: EncryptedText;
}
export interface UserProfile {
    name: string;
    email: string;
    organization: string;
}
export type EncryptedText = string;
export enum Status {
    scheduled = "scheduled",
    closed = "closed",
    reviewingEvidence = "reviewingEvidence",
    open = "open",
    awaitingCourt = "awaitingCourt"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCase(newCase: EncryptedCase): Promise<void>;
    addEvidence(caseNumber: EncryptedText, evidence: EncryptedText): Promise<void>;
    addHearing(caseNumber: EncryptedText, hearing: Hearing): Promise<void>;
    addMultipleCases(cases: Array<EncryptedCase>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCase(caseNumber: EncryptedText): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCaseByNumber(caseNumber: EncryptedText): Promise<EncryptedCase | null>;
    getCases(): Promise<Array<EncryptedCase>>;
    getCasesByStatus(status: Status): Promise<Array<EncryptedCase>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCase(updatedCase: EncryptedCase): Promise<void>;
    updateStatus(caseNumber: EncryptedText, newStatus: Status): Promise<void>;
}
import type { EncryptedCase as _EncryptedCase, EncryptedText as _EncryptedText, Hearing as _Hearing, Status as _Status, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCase(arg0: EncryptedCase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCase(to_candid_EncryptedCase_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCase(to_candid_EncryptedCase_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEvidence(arg0: EncryptedText, arg1: EncryptedText): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvidence(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvidence(arg0, arg1);
            return result;
        }
    }
    async addHearing(arg0: EncryptedText, arg1: Hearing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHearing(arg0, to_candid_Hearing_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHearing(arg0, to_candid_Hearing_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addMultipleCases(arg0: Array<EncryptedCase>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMultipleCases(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMultipleCases(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCase(arg0: EncryptedText): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCase(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseByNumber(arg0: EncryptedText): Promise<EncryptedCase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseByNumber(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseByNumber(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCases(): Promise<Array<EncryptedCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCases();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCases();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCasesByStatus(arg0: Status): Promise<Array<EncryptedCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCasesByStatus(to_candid_Status_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCasesByStatus(to_candid_Status_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCase(arg0: EncryptedCase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCase(to_candid_EncryptedCase_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCase(to_candid_EncryptedCase_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStatus(arg0: EncryptedText, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStatus(arg0, to_candid_Status_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStatus(arg0, to_candid_Status_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EncryptedCase_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EncryptedCase): EncryptedCase {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Hearing_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Hearing): Hearing {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EncryptedCase]): EncryptedCase | null {
    return value.length === 0 ? null : from_candid_EncryptedCase_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    clientName: _EncryptedText;
    caseNumber: _EncryptedText;
    nextHearing: _EncryptedText;
    hearings: Array<_Hearing>;
    creationDate: _EncryptedText;
    evidence: Array<_EncryptedText>;
    clientContact: _EncryptedText;
}): {
    status: Status;
    clientName: EncryptedText;
    caseNumber: EncryptedText;
    nextHearing: EncryptedText;
    hearings: Array<Hearing>;
    creationDate: EncryptedText;
    evidence: Array<EncryptedText>;
    clientContact: EncryptedText;
} {
    return {
        status: from_candid_Status_n17(_uploadFile, _downloadFile, value.status),
        clientName: value.clientName,
        caseNumber: value.caseNumber,
        nextHearing: value.nextHearing,
        hearings: from_candid_vec_n19(_uploadFile, _downloadFile, value.hearings),
        creationDate: value.creationDate,
        evidence: value.evidence,
        clientContact: value.clientContact
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    date: _EncryptedText;
    notes: _EncryptedText;
    outcome: _EncryptedText;
}): {
    status: Status;
    date: EncryptedText;
    notes: EncryptedText;
    outcome: EncryptedText;
} {
    return {
        status: from_candid_Status_n17(_uploadFile, _downloadFile, value.status),
        date: value.date,
        notes: value.notes,
        outcome: value.outcome
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    closed: null;
} | {
    reviewingEvidence: null;
} | {
    open: null;
} | {
    awaitingCourt: null;
}): Status {
    return "scheduled" in value ? Status.scheduled : "closed" in value ? Status.closed : "reviewingEvidence" in value ? Status.reviewingEvidence : "open" in value ? Status.open : "awaitingCourt" in value ? Status.awaitingCourt : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Hearing>): Array<Hearing> {
    return value.map((x)=>from_candid_Hearing_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EncryptedCase>): Array<EncryptedCase> {
    return value.map((x)=>from_candid_EncryptedCase_n15(_uploadFile, _downloadFile, x));
}
function to_candid_EncryptedCase_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EncryptedCase): _EncryptedCase {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Hearing_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Hearing): _Hearing {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    clientName: EncryptedText;
    caseNumber: EncryptedText;
    nextHearing: EncryptedText;
    hearings: Array<Hearing>;
    creationDate: EncryptedText;
    evidence: Array<EncryptedText>;
    clientContact: EncryptedText;
}): {
    status: _Status;
    clientName: _EncryptedText;
    caseNumber: _EncryptedText;
    nextHearing: _EncryptedText;
    hearings: Array<_Hearing>;
    creationDate: _EncryptedText;
    evidence: Array<_EncryptedText>;
    clientContact: _EncryptedText;
} {
    return {
        status: to_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        clientName: value.clientName,
        caseNumber: value.caseNumber,
        nextHearing: value.nextHearing,
        hearings: to_candid_vec_n5(_uploadFile, _downloadFile, value.hearings),
        creationDate: value.creationDate,
        evidence: value.evidence,
        clientContact: value.clientContact
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    date: EncryptedText;
    notes: EncryptedText;
    outcome: EncryptedText;
}): {
    status: _Status;
    date: _EncryptedText;
    notes: _EncryptedText;
    outcome: _EncryptedText;
} {
    return {
        status: to_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        date: value.date,
        notes: value.notes,
        outcome: value.outcome
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    scheduled: null;
} | {
    closed: null;
} | {
    reviewingEvidence: null;
} | {
    open: null;
} | {
    awaitingCourt: null;
} {
    return value == Status.scheduled ? {
        scheduled: null
    } : value == Status.closed ? {
        closed: null
    } : value == Status.reviewingEvidence ? {
        reviewingEvidence: null
    } : value == Status.open ? {
        open: null
    } : value == Status.awaitingCourt ? {
        awaitingCourt: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Hearing>): Array<_Hearing> {
    return value.map((x)=>to_candid_Hearing_n6(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EncryptedCase>): Array<_EncryptedCase> {
    return value.map((x)=>to_candid_EncryptedCase_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
